[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["cd backend && npm install"]

[phases.build]
cmds = ["cd backend && npx prisma generate && npm run build"]

[start]
cmd = "cd backend && npx prisma db push && npm run start:prod"

